using SharedEditor.Editor.Utils;
using UnityEditor;

namespace Shared.Service.Ads.Editor
{
    [InitializeOnLoad]
    public class AdsEditor
    {
        private const string ClassText = @"/* Generated by CodeGen, don't modify it. Please ask your Manager */
using Shared;
using Shared.Core.Handler;
using Shared.Core.IoC;
using Shared.Service.Ads;
using Shared.Service.Loading.Handlers;
using Shared.Utils;
using Zenject;

namespace Service.Loading
{
    [Component]
    public class AdsInitHandler : IHandler, IPostInitHandler, ISharedUtility
    {
        [Inject(Optional = true)] private IAdService _adService;
        
        public void Handle()
        {
            this.LogInfo();
            _adService?.BannerAd.LoadBanner();
            _adService?.InterstitialAd.StartLoadLoop();
            _adService?.RewardAd.StartLoadLoop();
        }
    }
}
";
        static AdsEditor()
        {
            EditorApplication.delayCall += OnAfterDomainReload;
        }

        private static void OnAfterDomainReload()
        {
#if CODE_GEN_ADS && LEVEL_PLAY
            _ = SharedEditorUtils.WriteProjectRelativeFile("Assets/Scripts/Service/Loading/AdsInitHandler.cs", ClassText, silent: true);
#else
            SharedEditorUtils.DeleteProjectRelativeFile("Assets/Scripts/Service/Loading/AdsInitHandler.cs", silent: true);   
#endif
            EditorApplication.delayCall -= OnAfterDomainReload;
#if ENABLE_SHARED_EDITOR_LOGGER
            Debug.Log("✅ AdsEditor Domain reload complete!");
#endif
        }
    }
}