using SharedEditor.Editor.Utils;
using UnityEditor;
using UnityEngine;

namespace Game.Shared.Editor
{
    [InitializeOnLoad]
    public class FastlaneFileBuilder
    {
        // fastlane/Pluginfile
        private const string PluginFileContent = @"# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

gem 'fastlane-plugin-firebase_app_distribution'
gem 'fastlane-plugin-huawei_appgallery_connect'
gem 'fastlane-plugin-checks'
";
      
        // Gemfile
        private const string GemFileContent = @"# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source ""https://rubygems.org""

gem 'fastlane'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
";

        static FastlaneFileBuilder()
        {
            EditorApplication.delayCall += OnAfterDomainReload;
        }

        private static void OnAfterDomainReload()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode)
            {
                EditorApplication.delayCall -= OnAfterDomainReload;
                return;
            }
            if (!SharedEditorUtils.IsProjectRelativeFileExisted("Gemfile"))
            {
                _ = SharedEditorUtils.WriteProjectRelativeFile("Gemfile", GemFileContent, silent: true);
            }
            if (!SharedEditorUtils.IsProjectRelativeFileExisted("fastlane/Pluginfile"))
            {
                _ = SharedEditorUtils.WriteProjectRelativeFile("fastlane/Pluginfile", PluginFileContent,  silent: true);
            }
            
            EditorApplication.delayCall -= OnAfterDomainReload;
#if ENABLE_SHARED_EDITOR_LOGGER
            Debug.Log("✅ FastlaneFileBuilder Domain reload complete!");
#endif
        }
    }
}