using SharedEditor.Editor.Utils;
using UnityEditor;
using UnityEngine;

namespace Shared.Editor
{
    [InitializeOnLoad]
    public class JavaUserInfoControllerFileBuilder
    {
        private static string fileContent = @"
/** Generated by CodeGen, don't modify it. Please ask your Manager **/
package com.unity3d.player;

import android.provider.Settings;

public class UserInfoController {

    public static String getAndroidId() {
        return Settings.Secure.getString(UnityPlayer.currentActivity.getContentResolver(), Settings.Secure.ANDROID_ID);
    }

}";
        static JavaUserInfoControllerFileBuilder()
        {
            EditorApplication.delayCall += OnAfterDomainReload;
        }
        
        private static void OnAfterDomainReload()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode)
            {
                EditorApplication.delayCall -= OnAfterDomainReload;
                return;
            }
            _ = SharedEditorUtils.WriteProjectRelativeFile("Assets/Plugins/Android/UserInfoController.java", fileContent, silent: true);
            EditorApplication.delayCall -= OnAfterDomainReload;
#if ENABLE_SHARED_EDITOR_LOGGER
            Debug.Log("✅ JavaUserInfoControllerFileBuilder Domain reload complete!");
#endif
        }
    }
}