using SharedEditor.Editor.Utils;
using UnityEditor;

namespace Shared.Editor
{
    [InitializeOnLoad]
    public class JavaUnityPlayerActivityWithANRWatchDogFileBuilder
    {
        private const string FireBaseContent = @"
/** Generated by CodeGen, don't modify it. Please ask your Manager **/
package com.unity3d.player;

import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.os.Bundle;
import com.github.anrwatchdog.ANRWatchDog;
import com.google.firebase.MessagingUnityPlayerActivity;
import android.util.Log;
import android.provider.Settings.Secure;

// https://github.com/SalomonBrys/ANR-WatchDog/blob/master/testapp/src/main/java/com/github/anrtestapp/MainActivity.java
public class UnityPlayerActivityWithANRWatchDog extends MessagingUnityPlayerActivity {
    private static final String TAG = ""UnityPlayerActivityWithANRWatchDog"";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Log.i(TAG, ""onCreate. -> new ANRWatchDog"");
        new ANRWatchDog(4500).setIgnoreDebugger(true).setReportMainThreadOnly().setANRListener(error -> {
            Log.i(TAG, ""ANR detected"");
            System.out.println(""ANR detected"");
            restartApp();
        }).start();
    }

    public void restartApp()
    {
        Log.i(TAG, ""restartApp"");
        Context context = UnityPlayerActivityWithANRWatchDog.this;
        PackageManager packageManager = context.getPackageManager();
        Intent intent = packageManager.getLaunchIntentForPackage(context.getPackageName());
        ComponentName componentName = intent.getComponent();
        Intent mainIntent = Intent.makeRestartActivityTask(componentName);
        context.startActivity(mainIntent);
        Runtime.getRuntime().exit(0);
    }

    public String getAndroidId() {
        return Secure.getString(getContentResolver(), Secure.ANDROID_ID);
    }
}";
        
        private const string NonFireBaseContent = @"
/** Generated by CodeGen, don't modify it. Please ask your Manager **/
package com.unity3d.player;

import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.os.Bundle;
import com.github.anrwatchdog.ANRWatchDog;
import android.util.Log;
import android.provider.Settings.Secure;

// https://github.com/SalomonBrys/ANR-WatchDog/blob/master/testapp/src/main/java/com/github/anrtestapp/MainActivity.java
public class UnityPlayerActivityWithANRWatchDog extends UnityPlayerActivity {
    private static final String TAG = ""UnityPlayerActivityWithANRWatchDog"";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Log.i(TAG, ""onCreate. -> new ANRWatchDog"");
        new ANRWatchDog(4500).setIgnoreDebugger(true).setReportMainThreadOnly().setANRListener(error -> {
            Log.i(TAG, ""ANR detected"");
            System.out.println(""ANR detected"");
            restartApp();
        }).start();
    }

    public void restartApp()
    {
        Log.i(TAG, ""restartApp"");
        Context context = UnityPlayerActivityWithANRWatchDog.this;
        PackageManager packageManager = context.getPackageManager();
        Intent intent = packageManager.getLaunchIntentForPackage(context.getPackageName());
        ComponentName componentName = intent.getComponent();
        Intent mainIntent = Intent.makeRestartActivityTask(componentName);
        context.startActivity(mainIntent);
        Runtime.getRuntime().exit(0);
    }

    public String getAndroidId() {
        return Secure.getString(getContentResolver(), Secure.ANDROID_ID);
    }
}";

        static JavaUnityPlayerActivityWithANRWatchDogFileBuilder()
        {
            EditorApplication.delayCall += OnAfterDomainReload;
        }
        
        private static void OnAfterDomainReload()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode)
            {
                EditorApplication.delayCall -= OnAfterDomainReload;
                return;
            }
            var content = NonFireBaseContent;
#if GOOGLE_FIREBASE_MESSAGING
            content = FireBaseContent;
#endif
            _ = SharedEditorUtils.WriteProjectRelativeFile("Assets/Plugins/Android/UnityPlayerActivityWithANRWatchDog.java", content, silent: true);
            EditorApplication.delayCall -= OnAfterDomainReload;
#if ENABLE_SHARED_EDITOR_LOGGER
            UnityEngine.Debug.Log("✅ JavaUnityPlayerActivityWithANRWatchDogFileBuilder Domain reload complete!");
#endif
        }
    }
}