/* Generated by CodeGen, don't modify it. Please ask your Manager */
package com.unity3d.player;

import android.app.Activity;
import android.app.ActivityManager;
import android.app.ApplicationExitInfo;
import android.content.Context;
import androidx.annotation.RequiresApi;
import java.util.List;

public class CrashReporter {
    @RequiresApi(api = 30)
    public static int getExitReason(Activity context) {
        Context ac = context.getApplicationContext();
        ActivityManager am = (ActivityManager)ac.getApplicationContext().getSystemService(Context.ACTIVITY_SERVICE);
        List<ApplicationExitInfo> exitList = am.getHistoricalProcessExitReasons(ac.getPackageName(), 0, 1);
        if (!exitList.isEmpty()) {
            ApplicationExitInfo lastExitInformation = exitList.get(0);
            return lastExitInformation.getReason();
        }
        return -1;
    }
}