
/** Generated by CodeGen, don't modify it. Please ask your Manager **/
package com.unity3d.player;

import androidx.annotation.Nullable;

public interface IAndroidApplicationLifeCycleListener {
    void onCreate();
    void onActivityCreated(@Nullable String activityName);
    void onActivityStarted(@Nullable String activityName);
    void onActivityResumed(@Nullable String activityName);
    void onActivityPaused(@Nullable String activityName);
    void onActivityStopped(@Nullable String activityName);
    void onActivitySaveInstanceState(@Nullable String activityName);
    void onActivityDestroyed(@Nullable String activityName);
}