
/** Generated by CodeGen, don't modify it. Please ask your Manager **/
package com.unity3d.player;

public interface IUnityInstallReferrerCallback {
    void onInstallReferrerSetupFinished(int responseCode);
    void onInstallReferrerServiceDisconnected();
}