
/** Generated by CodeGen, don't modify it. Please ask your Manager **/
package com.unity3d.player;

import android.app.Activity;
import android.app.Application;
import android.os.Bundle;
import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public class MyApplication extends Application implements Application.ActivityLifecycleCallbacks {

    private static final String TAG = "MyApplication";

    public static MyApplication instance;

    public static MyApplication getInstance()
    {
        return instance;
    }

    private IAndroidApplicationLifeCycleListener listener;

    public void setAndroidApplicationLifeCycleListener(IAndroidApplicationLifeCycleListener listener) {
       this.listener = listener;
    }

    @Override
    public void onCreate() {
        super.onCreate();
        registerActivityLifecycleCallbacks(this);
        if(listener != null) listener.onCreate();
    }

    @Override
    public void onActivityCreated(@NonNull Activity activity, @Nullable Bundle bundle) {
        var activityName = activity.getClass().getName();
        Log.i(TAG, "onActivityCreated: " + activityName);
        if (instance == null) instance = this;
        if(listener != null) listener.onActivityCreated(activityName);
    }

    @Override
    public void onActivityStarted(@NonNull Activity activity) {
        var activityName = activity.getClass().getName();
        Log.i(TAG, "onActivityStarted: " + activityName);
        if(listener != null) listener.onActivityStarted(activityName);
    }

    @Override
    public void onActivityResumed(@NonNull Activity activity) {
        var activityName = activity.getClass().getName();
        Log.i(TAG, "onActivityResumed: " + activityName);
        if(listener != null) listener.onActivityResumed(activityName);
    }

    @Override
    public void onActivityPaused(@NonNull Activity activity) {
        var activityName = activity.getClass().getName();
        Log.i(TAG, "onActivityPaused: " + activityName);
        if(listener != null) listener.onActivityPaused(activityName);
    }

    @Override
    public void onActivityStopped(@NonNull Activity activity) {
        var activityName = activity.getClass().getName();
        Log.i(TAG, "onActivityStopped: " + activityName);
        if(listener != null) listener.onActivityStopped(activityName);
    }

    @Override
    public void onActivitySaveInstanceState(@NonNull Activity activity, @NonNull Bundle bundle) {
        var activityName = activity.getClass().getName();
        Log.i(TAG, "onActivitySaveInstanceState: " + activityName);
        if(listener != null) listener.onActivitySaveInstanceState(activityName);
    }

    @Override
    public void onActivityDestroyed(@NonNull Activity activity) {
        var activityName = activity.getClass().getName();
        Log.i(TAG, "onActivityDestroyed: " + activityName);
        if(listener != null) listener.onActivityDestroyed(activityName);
    }
}