
/** Generated by CodeGen, don't modify it. Please ask your Manager **/
package com.unity3d.player;

import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.os.Bundle;
import com.github.anrwatchdog.ANRWatchDog;
import android.util.Log;
import android.provider.Settings.Secure;

// https://github.com/SalomonBrys/ANR-WatchDog/blob/master/testapp/src/main/java/com/github/anrtestapp/MainActivity.java
public class UnityPlayerActivityWithANRWatchDog extends UnityPlayerActivity {
    private static final String TAG = "UnityPlayerActivityWithANRWatchDog";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Log.i(TAG, "onCreate. -> new ANRWatchDog");
        new ANRWatchDog(4500).setIgnoreDebugger(true).setReportMainThreadOnly().setANRListener(error -> {
            Log.i(TAG, "ANR detected");
            System.out.println("ANR detected");
            restartApp();
        }).start();
    }

    public void restartApp()
    {
        Log.i(TAG, "restartApp");
        Context context = UnityPlayerActivityWithANRWatchDog.this;
        PackageManager packageManager = context.getPackageManager();
        Intent intent = packageManager.getLaunchIntentForPackage(context.getPackageName());
        ComponentName componentName = intent.getComponent();
        Intent mainIntent = Intent.makeRestartActivityTask(componentName);
        context.startActivity(mainIntent);
        Runtime.getRuntime().exit(0);
    }

    public String getAndroidId() {
        return Secure.getString(getContentResolver(), Secure.ANDROID_ID);
    }
}