
/** Generated by CodeGen, don't modify it. Please ask your Manager **/
package com.unity3d.player;

import android.provider.Settings;

public class UserInfoController {

    public static String getAndroidId() {
        return Settings.Secure.getString(UnityPlayer.currentActivity.getContentResolver(), Settings.Secure.ANDROID_ID);
    }

}