using System.IO;
using SharedEditor.Editor.Utils;
using UnityEditor;
using UnityEngine;

namespace Shared.Service.ParentControl.Editor
{
    [InitializeOnLoad]
    public class ParentControlEditor
    {
        private static readonly string ClassText = @"/* Generated by CodeGen, don't modify it. Please ask your Manager */
using Shared;
using Shared.Core.Handler;
using Shared.Core.IoC;
using Shared.Service.Loading.Handlers;
using Shared.Service.ParentControl;
using Shared.Utils;
using Zenject;

namespace Service.Loading
{
    [Component]
    public class ParentControlLoadingPostInitHandler : IHandler, IPostInitHandler, ISharedUtility
    {
        [Inject(Optional = true)] private IParentControlService _parentControlService;
        
        public void Handle()
        {
            this.LogInfo();
            _parentControlService?.Sync();
        }
    }
}";
        
        static ParentControlEditor()
        {
            EditorApplication.delayCall += OnAfterDomainReload;
        }

        private static void OnAfterDomainReload()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode)
            {
                EditorApplication.delayCall -= OnAfterDomainReload;
                return;
            }
#if CODE_GEN_PARENT_CONTROL && PARENT_CONTROL            
            _ = SharedEditorUtils.WriteProjectRelativeFile("Assets/Scripts/Service/Loading/ParentControlLoadingPostInitHandler.cs", ClassText, silent: true);
#else
            SharedEditorUtils.DeleteProjectRelativeFile("Assets/Scripts/Service/Loading/ParentControlLoadingPostInitHandler.cs", silent: true);
#endif
            EditorApplication.delayCall -= OnAfterDomainReload;
#if ENABLE_SHARED_EDITOR_LOGGER
            Debug.Log("✅ ParentControlEditor Domain reload complete!");
#endif
        }
    }
}
