using SharedEditor.Editor.Utils;
using UnityEditor;
using UnityEngine;

namespace Shared.Service.Referrer.Editor
{
    [InitializeOnLoad]
    public class JavaInstallReferrerControllerFileBuilder
    {
        private static string fileContent = @"
/** Generated by CodeGen, don't modify it. Please ask your Manager **/
package com.unity3d.player;

import android.os.RemoteException;
import com.android.installreferrer.api.InstallReferrerClient;
import com.android.installreferrer.api.InstallReferrerStateListener;
import com.android.installreferrer.api.ReferrerDetails;
import org.json.JSONObject;
import java.util.HashMap;
import java.util.Map;

// https://developer.android.com/google/play/installreferrer/library#java
public class InstallReferrerController {

    private static InstallReferrerController instance;
    public static InstallReferrerController getInstance() {
        if (instance == null) instance = new InstallReferrerController();
        return instance;
    }

    private IUnityInstallReferrerCallback callback;
    private InstallReferrerClient referrerClient;
    private int responseCode = 1989;

    public void setUnityInstallReferrerCallback(IUnityInstallReferrerCallback callback) {
        this.callback = callback;
    }

    public void connect() {
        referrerClient = InstallReferrerClient.newBuilder(UnityPlayer.currentActivity).build();
        referrerClient.startConnection(new InstallReferrerStateListener() {
            @Override
            public void onInstallReferrerSetupFinished(int responseCode) {
                instance.responseCode = responseCode;
                callback.onInstallReferrerSetupFinished(responseCode);
            }

            @Override
            public void onInstallReferrerServiceDisconnected() {
                // Try to restart the connection on the next request to
                // Google Play by calling the startConnection() method.
                callback.onInstallReferrerServiceDisconnected();
            }
        });
    }

    public boolean isConnected()
    {
        return referrerClient != null && responseCode == InstallReferrerClient.InstallReferrerResponse.OK;
    }

    public String getInstallReferrer() throws RemoteException {
        ReferrerDetails response = referrerClient.getInstallReferrer();
        Map<String, Object> data = new HashMap<>() {{
            put(""googlePlayInstantParam"", response.getGooglePlayInstantParam());

            put(""installReferrer"", response.getInstallReferrer());
            put(""installBeginTimestampSeconds"", response.getInstallBeginTimestampSeconds());
            put(""installBeginTimestampServerSeconds"", response.getInstallBeginTimestampServerSeconds());
            put(""installVersion"", response.getInstallVersion());

            put(""referrerClickTimestampSeconds"", response.getReferrerClickTimestampSeconds());
            put(""referrerClickTimestampServerSeconds"", response.getReferrerClickTimestampServerSeconds());
        }};
        JSONObject o = new JSONObject(data);
        return o.toString();
    }

    public void close()
    {
        if (isConnected())
        {
            referrerClient.endConnection();
            responseCode = 1989;
        }
    }
}";
        static JavaInstallReferrerControllerFileBuilder()
        {
            EditorApplication.delayCall += OnAfterDomainReload;
        }
        
        private static void OnAfterDomainReload()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode)
            {
                EditorApplication.delayCall -= OnAfterDomainReload;
                return;
            }
            
            _ = SharedEditorUtils.WriteProjectRelativeFile("Assets/Plugins/Android/InstallReferrerController.java", fileContent, silent: true);
            EditorApplication.delayCall -= OnAfterDomainReload;
#if ENABLE_SHARED_EDITOR_LOGGER
            Debug.Log("✅ JavaInstallReferrerControllerFileBuilder Domain reload complete!");
#endif
        }
    }
}