using SharedEditor.Editor.Utils;
using UnityEditor;
using UnityEngine;

namespace SharedEditor.Editor.Distribution.StorePlugin
{
    [InitializeOnLoad]
    public class JavaIUnityInstallReferrerCallbackFileBuilder
    {
        private static readonly string fileContent = @"
/** Generated by CodeGen, don't modify it. Please ask your Manager **/
package com.unity3d.player;

public interface IUnityInstallReferrerCallback {
    void onInstallReferrerSetupFinished(int responseCode);
    void onInstallReferrerServiceDisconnected();
}";

        static JavaIUnityInstallReferrerCallbackFileBuilder()
        {
            EditorApplication.delayCall += OnAfterDomainReload;
        }
        
        private static void OnAfterDomainReload()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode)
            {
                EditorApplication.delayCall -= OnAfterDomainReload;
                return;
            }
            _ = SharedEditorUtils.WriteProjectRelativeFile("Assets/Plugins/Android/IUnityInstallReferrerCallback.java", fileContent, silent: true);
            EditorApplication.delayCall -= OnAfterDomainReload;
#if ENABLE_SHARED_EDITOR_LOGGER
            Debug.Log("✅ JavaIUnityInstallReferrerCallbackFileBuilder Domain reload complete!");
#endif
        }
    }
}