using SharedEditor.Editor.Utils;
using UnityEditor;

namespace Shared.Service.FirebaseRemoteConfig.Editor
{
    [InitializeOnLoad]
    public class RemoteConfigEditor
    {
        private const string ClassText = @"/* Generated by CodeGen, don't modify it. Please ask your Manager */
using Shared;
using Shared.Core.Handler;
using Shared.Core.IoC;
using Shared.Service.FirebaseRemoteConfig;
using Shared.Service.Loading.Handlers;
using Shared.Utils;
using Zenject;

namespace Service.Loading
{
    [Component]
    public class RemoteConfigPostLoadingInitHandler : IHandler, IPostInitHandler, ISharedUtility
    {
        [Inject(Optional = true)] private IFirebaseRemoteConfigService _remoteConfigService;
        
        public void Handle()
        {
            this.LogInfo();
            _remoteConfigService?.ProcessAbTestingDetector();
        }
    }
}
";
        static RemoteConfigEditor()
        {
            EditorApplication.delayCall += OnAfterDomainReload;
        }

        private static void OnAfterDomainReload()
        {
#if CODE_GEN_REMOTE_CONFIG && FIREBASE
            _ = SharedEditorUtils.WriteProjectRelativeFile("Assets/Scripts/Service/Loading/RemoteConfigPostLoadingInitHandler.cs", ClassText, silent: true);
#else
            SharedEditorUtils.DeleteProjectRelativeFile("Assets/Scripts/Service/Loading/RemoteConfigPostLoadingInitHandler.cs", silent: true);
#endif
            EditorApplication.delayCall -= OnAfterDomainReload;
#if ENABLE_SHARED_EDITOR_LOGGER
            Debug.Log("✅ RemoteConfigEditor Domain reload complete!");
#endif
        }
    }
}