using SharedEditor.Editor.Utils;
using UnityEditor;
using UnityEngine;

namespace SharedEditor.Editor.Distribution.StorePlugin
{
    [InitializeOnLoad]
    public class JavaIAndroidApplicationLifeCycleListenerFileBuilder
    {
        private static readonly string javaCode = @"
/** Generated by CodeGen, don't modify it. Please ask your Manager **/
package com.unity3d.player;

import androidx.annotation.Nullable;

public interface IAndroidApplicationLifeCycleListener {
    void onCreate();
    void onActivityCreated(@Nullable String activityName);
    void onActivityStarted(@Nullable String activityName);
    void onActivityResumed(@Nullable String activityName);
    void onActivityPaused(@Nullable String activityName);
    void onActivityStopped(@Nullable String activityName);
    void onActivitySaveInstanceState(@Nullable String activityName);
    void onActivityDestroyed(@Nullable String activityName);
}";
        static JavaIAndroidApplicationLifeCycleListenerFileBuilder()
        {
            EditorApplication.delayCall += OnAfterDomainReload;
        }
        
        private static void OnAfterDomainReload()
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode)
            {
                EditorApplication.delayCall -= OnAfterDomainReload;
                return;
            }
            _ = SharedEditorUtils.WriteProjectRelativeFile("Assets/Plugins/Android/IAndroidApplicationLifeCycleListener.java", javaCode, silent: true);
            EditorApplication.delayCall -= OnAfterDomainReload;
#if ENABLE_SHARED_EDITOR_LOGGER
            Debug.Log("✅ JavaIAndroidApplicationLifeCycleListenerFileBuilder Domain reload complete!");
#endif
        }
    }
}